joint_limits:
  arm1_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0.0
    min_effort: 0.0
  arm2_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0.0
    min_effort: 0.0
  arm3_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0.0
    min_effort: 0.0
  arm4_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0.0
    min_effort: 0.0
  arm5_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0.0
    min_effort: 0.0
  arm6_joint:
    has_position_limits: true
    min_position: -1.57
    max_position: 1.57
    has_velocity_limits: false
    max_velocity: 0.0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 0.0
    min_effort: 0.0